# .github/release.yml

changelog:
  categories:
    - title: Highlights 🌟
      labels:
        - Highlights
   
    - title: New Features 🚀
      labels:
        - feature
        - enhancement
    
    - title: Bug Fixes 🐛
      labels:
        - bug
    
    - title: Documentation 📚
      labels:
        - documentation
    
    - title: Other Changes
      labels:
        - "*"
